# Generated by Django 4.2.2 on 2023-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_image_project_image_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(choices=[('property', 'Property'), ('construction', 'Construction'), ('ict', 'ICT'), ('food', 'Food and Farming')], default=property, max_length=255),
            preserve_default=False,
        ),
    ]
