# Generated by Django 4.2.2 on 2023-06-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
    ]
