# Generated by Django 4.2.2 on 2023-06-20 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be less than 0.'), django.core.validators.MaxValueValidator(100, message='Value cannot be greater than 100.')]),
        ),
    ]
