# Generated by Django 4.2.2 on 2023-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_partnerslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='popularity',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='blog',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerslider',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
