# Generated by Django 4.2.2 on 2023-06-20 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_popularity_service_priority_blog_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=500)),
                ('phone', models.CharField(default='N/A', max_length=500)),
                ('email', models.CharField(default='N/A', max_length=500)),
                ('message', models.CharField(default='N/A', max_length=10000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
    ]
