# Generated by Django 4.2.2 on 2023-06-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_homeslider_title_remove_project_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='location',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
