# Generated by Django 4.2.2 on 2023-06-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_quote_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sub_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subservice'),
        ),
    ]
