# Generated by Django 4.2.2 on 2023-06-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_quote_sub_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
