# Generated by Django 4.2.2 on 2023-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_service_slug_alter_subservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
