# Generated by Django 4.2.2 on 2023-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_blog_slug_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, default='n/a', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, default='n/a', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
