# Generated by Django 4.2.2 on 2023-06-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_blog_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Estimate', 'verbose_name_plural': 'Estimates'},
        ),
    ]
