# Generated by Django 4.2.2 on 2023-06-21 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_quote_options_alter_project_sub_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=500)),
                ('phone', models.CharField(default='N/A', max_length=500)),
                ('email', models.CharField(default='N/A', max_length=500)),
                ('message', models.CharField(default='N/A', max_length=10000)),
                ('location', models.CharField(default='N/A', max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
