# Generated by Django 3.2.18 on 2023-06-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_contactus_options_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subservice'),
        ),
    ]
