# Generated by Django 3.2.18 on 2023-06-24 16:25

from django.db import migrations, models
import django.utils.timezone
import main.models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, main.models.ImageUrl),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=main.utils.unique_id, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(to='main.ProductImage'),
        ),
    ]
