# Generated by Django 3.2.18 on 2023-06-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20230624_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
