# Generated by Django 3.2.18 on 2023-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
