# Generated by Django 3.2.18 on 2023-06-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20230625_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email Subscriber', 'verbose_name_plural': 'Email Subscribers'},
        ),
    ]
