# Generated by Django 3.2.18 on 2023-06-27 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_email_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partnerslider',
            name='company',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
