# Generated by Django 3.2.18 on 2023-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_quote_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('Enugu Branch', 'Enugu Branch'), ('Port Harcourt Branch', 'Port Harcourt Branch')], default='Enugu Branch', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='location',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
