# Generated by Django 3.2.18 on 2023-06-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_budget',
        ),
    ]
