# Generated by Django 3.2.18 on 2023-06-29 13:37

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20230629_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
